# Generated by Django 5.1.1 on 2024-09-11 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0001_initial"),
        ("posts", "0002_alter_post_options_remove_post_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="posts.post",
            ),
        ),
    ]
