# Generated by Django 5.1.1 on 2024-09-11 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("followers", "0002_alter_follower_follower_alter_follower_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="follower",
            new_name="followed",
        ),
        migrations.AlterUniqueTogether(
            name="follower",
            unique_together={("owner", "followed")},
        ),
    ]
